name: Build and Release APK

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0

  workflow_dispatch: # Manual trigger support

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source code
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      # Step 2: Set up JDK 17 using Temurin distribution
      - name: Set Up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          distribution: "temurin"
          java-version: "17"

      # Step 3: Make Gradle wrapper executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # Step 4: Configure signing credentials
      - name: Set Up Keystore for Signing
        run: |
          mkdir -p keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore/keystore.jks
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore/keystore.properties

      # Step 5: Build the release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Step 6: Create GitHub Release and attach APK
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Release ${{ github.ref_name }}" # e.g., Release v1.0
          tag_name: ${{ github.ref_name }}
          body: |
            🔖 Version: ${{ github.ref_name }}
            🔧 Commit: ${{ github.sha }}
            📦 This release contains the signed release APK.
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
